### ISSUE TITLE
U-BOOT打补丁失败

### ISSUE THREAD

**Issue by jadqin** [Izumiko/uboot-tqc-a01#1]
Building U-Boot
patching file arch/arm/dts/Makefile
Hunk #1 FAILED at 642.
1 out of 1 hunk FAILED -- saving rejects to file arch/arm/dts/Makefile.rej
patching file arch/arm/dts/sun50i-h6-tqc-a01.dts
patching file arch/arm/dts/sun50i-h6.dtsi
Hunk #1 succeeded at 17 (offset 1 line).
Hunk #2 succeeded at 286 (offset 10 lines).
Hunk #3 succeeded at 346 (offset 19 lines).
Hunk #4 succeeded at 374 (offset 19 lines).
Hunk #5 succeeded at 643 (offset 19 lines).
patching file configs/tqc_a01_defconfig
patching file cmd/Kconfig
Hunk #1 FAILED at 1662.
1 out of 1 hunk FAILED -- saving rejects to file cmd/Kconfig.rej
patching file include/config_distro_bootcmd.h
Hunk #1 succeeded at 469 with fuzz 2 (offset 39 lines).
patching file include/configs/sunxi-common.h
Hunk #1 succeeded at 106 with fuzz 1 (offset -117 lines).
Hunk #2 succeeded at 296 (offset -108 lines).
patching file arch/arm/Kconfig
Hunk #1 succeeded at 1121 (offset -59 lines).
patching file boot/Kconfig
Hunk #1 succeeded at 1189 (offset 186 lines).
Hunk #2 succeeded at 1244 (offset 186 lines).
patching file cmd/fdt.c
Hunk #1 succeeded at 18 (offset 1 line).
Hunk #2 succeeded at 803 (offset 21 lines).
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  YACC    scripts/kconfig/zconf.tab.c
  LEX     scripts/kconfig/zconf.lex.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
\#
\# configuration written to .config
\#
scripts/kconfig/conf  --syncconfig Kconfig
  UPD     include/config.h
  CFG     u-boot.cfg
  GEN     include/autoconf.mk
  GEN     include/autoconf.mk.dep
  CFG     spl/u-boot.cfg
  GEN     spl/include/autoconf.mk
  UPD     include/config/uboot.release
  UPD     include/generated/version_autogenerated.h
  UPD     include/generated/timestamp_autogenerated.h
  UPD     include/generated/dt.h
  ENVC    include/generated/env.txt
  ENVP    include/generated/env.in
  ENVT    include/generated/environment.h
  CC      lib/asm-offsets.s
  UPD     include/generated/generic-asm-offsets.h
  CC      arch/arm/lib/asm-offsets.s
  UPD     include/generated/asm-offsets.h
  SHIPPED scripts/dtc/pylibfdt/libfdt.i
  PYMOD   rebuild
Traceback (most recent call last):
  File "scripts/dtc/pylibfdt/setup.py", line 23, in <module>
    from setuptools import setup, Extension
ModuleNotFoundError: No module named 'setuptools'
scripts/dtc/pylibfdt/Makefile:30: recipe for target 'rebuild' failed
make[2]: *** [rebuild] Error 1
scripts/Makefile.build:398: recipe for target 'scripts/dtc/pylibfdt' failed
make[1]: *** [scripts/dtc/pylibfdt] Error 2
Makefile:2031: recipe for target 'scripts_dtc' failed
make: *** [scripts_dtc] Error 2

**Comment by Izumiko** [comment]
升级到了最新版 https://github.com/Izumiko/uboot-tqc-a01/releases/tag/v2024.07 ，还未测试

**Comment by jadqin** [comment]
> 升级到了最新版 https://github.com/Izumiko/uboot-tqc-a01/releases/tag/v2024.07 ，还未测试

编译U-Boot报错：
tools/sunxi_toc0.o: In function \`toc0_verify_header\':
sunxi_toc0.c:(.text+0x541): undefined reference to \`RSA_get0_n\'

**Comment by Izumiko** [comment]
你是怎么编译的？我的编译log里面没报错
https://github.com/Izumiko/uboot-tqc-a01/actions/runs/9918837253/job/27404004026

**Comment by jadqin** [comment]
> 你是怎么编译的？我的编译log里面没报错 https://github.com/Izumiko/uboot-tqc-a01/actions/runs/9918837253/job/27404004026

可能是我的python版本不对？
Building U-Boot
  CLEAN   tools
  CLEAN   tools/generated
  CLEAN   spl/u-boot.cfg
  CLEAN   include/autoconf.mk include/autoconf.mk.dep include/config.h include/generated/env.in include/generated/env.txt u-boot.cfg
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  YACC    scripts/kconfig/zconf.tab.c
  LEX     scripts/kconfig/zconf.lex.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
\#
\# configuration written to .config
\#
scripts/kconfig/conf  --syncconfig Kconfig
  UPD     include/config.h
  CFG     spl/u-boot.cfg
  GEN     spl/include/autoconf.mk
  CFG     u-boot.cfg
  GEN     include/autoconf.mk
  GEN     include/autoconf.mk.dep
  UPD     include/generated/timestamp_autogenerated.h
  ENVC    include/generated/env.txt
  ENVP    include/generated/env.in
  ENVT    include/generated/environment.h
  CC      lib/asm-offsets.s
  CC      arch/arm/lib/asm-offsets.s
  PYMOD   rebuild
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'license_files'
  warnings.warn(msg)
/usr/lib/python3/dist-packages/setuptools/dist.py:397: UserWarning: Normalizing '2024.07' to '2024.7'
  normalized_version,
  HOSTCC  scripts/dtc/dtc.o
  HOSTCC  scripts/dtc/flattree.o
  HOSTCC  scripts/dtc/fstree.o
  HOSTCC  scripts/dtc/data.o
  HOSTCC  scripts/dtc/livetree.o
  HOSTCC  scripts/dtc/treesource.o
  HOSTCC  scripts/dtc/srcpos.o
  HOSTCC  scripts/dtc/checks.o
  HOSTCC  scripts/dtc/util.o
  LEX     scripts/dtc/dtc-lexer.lex.c
  YACC    scripts/dtc/dtc-parser.tab.h
  HOSTCC  scripts/dtc/dtc-lexer.lex.o
  YACC    scripts/dtc/dtc-parser.tab.c
  HOSTCC  scripts/dtc/dtc-parser.tab.o
  HOSTLD  scripts/dtc/dtc
  HOSTCC  tools/gen_eth_addr
  HOSTCC  tools/gen_ethaddr_crc.o
  WRAP    tools/generated/lib/crc8.c
  HOSTCC  tools/generated/lib/crc8.o
  HOSTLD  tools/gen_ethaddr_crc
  HOSTCC  tools/img2srec
  HOSTCC  tools/mkenvimage.o
  HOSTCC  tools/os_support.o
  WRAP    tools/generated/lib/crc32.c
  HOSTCC  tools/generated/lib/crc32.o
  HOSTLD  tools/mkenvimage
  HOSTCC  tools/aisimage.o
  HOSTCC  tools/atmelimage.o
  HOSTCC  tools/fit_common.o
  HOSTCC  tools/fit_image.o
  HOSTCC  tools/image-host.o
  WRAP    tools/generated/boot/image-fit.c
  HOSTCC  tools/generated/boot/image-fit.o
  HOSTCC  tools/image-sig-host.o
  WRAP    tools/generated/boot/image-fit-sig.c
  HOSTCC  tools/generated/boot/image-fit-sig.o
WRAP    tools/generated/boot/image-cipher.c
  HOSTCC  tools/generated/boot/image-cipher.o
  WRAP    tools/generated/boot/fdt_region.c
  HOSTCC  tools/generated/boot/fdt_region.o
  WRAP    tools/generated/boot/bootm.c
  HOSTCC  tools/generated/boot/bootm.o
  HOSTCC  tools/default_image.o
  WRAP    tools/generated/lib/fdtdec_common.c
  HOSTCC  tools/generated/lib/fdtdec_common.o
  WRAP    tools/generated/lib/fdtdec.c
  HOSTCC  tools/generated/lib/fdtdec.o
  WRAP    tools/generated/boot/image.c
  HOSTCC  tools/generated/boot/image.o
  WRAP    tools/generated/boot/image-host.c
  HOSTCC  tools/generated/boot/image-host.o
  HOSTCC  tools/imagetool.o
  HOSTCC  tools/imximage.o
  HOSTCC  tools/imx8image.o
  HOSTCC  tools/imx8mimage.o
  HOSTCC  tools/kwbimage.o
  WRAP    tools/generated/lib/md5.c
  HOSTCC  tools/generated/lib/md5.o
  HOSTCC  tools/lpc32xximage.o
  HOSTCC  tools/mxsimage.o
  HOSTCC  tools/omapimage.o
  HOSTCC  tools/pblimage.o
  HOSTCC  tools/pbl_crc32.o
  HOSTCC  tools/renesas_spkgimage.o
  HOSTCC  tools/sfspl.o
  HOSTCC  tools/vybridimage.o
  HOSTCC  tools/stm32image.o
  WRAP    tools/generated/lib/rc4.c
  HOSTCC  tools/generated/lib/rc4.o
  HOSTCC  tools/rkcommon.o
  HOSTCC  tools/rkimage.o
  HOSTCC  tools/rksd.o
  HOSTCC  tools/rkspi.o
  HOSTCC  tools/socfpgaimage.o
  HOSTCC  tools/sunxi_egon.o
  WRAP    tools/generated/lib/crc16-ccitt.c
  HOSTCC  tools/generated/lib/crc16-ccitt.o
  WRAP    tools/generated/lib/hash-checksum.c
  HOSTCC  tools/generated/lib/hash-checksum.o
  WRAP    tools/generated/lib/sha1.c
  HOSTCC  tools/generated/lib/sha1.o
  WRAP    tools/generated/lib/sha256.c
  HOSTCC  tools/generated/lib/sha256.o
  WRAP    tools/generated/lib/sha512.c
  HOSTCC  tools/generated/lib/sha512.o
  WRAP    tools/generated/common/hash.c
  HOSTCC  tools/generated/common/hash.o
  HOSTCC  tools/ublimage.o
  HOSTCC  tools/zynqimage.o
  HOSTCC  tools/zynqmpimage.o
  HOSTCC  tools/zynqmpbif.o
  WRAP    tools/generated/lib/fdt-libcrypto.c
  HOSTCC  tools/generated/lib/fdt-libcrypto.o
  HOSTCC  tools/sunxi_toc0.o
tools/sunxi_toc0.c: In function ‘toc0_create_key_item’:
tools/sunxi_toc0.c:216:20: warning: implicit declaration of function ‘RSA_get0_n’; did you mean ‘RSA_get0_key’? [-Wimplicit-function-declaration]

**Comment by Izumiko** [comment]
python3.6的话有点老，要不你也跟我一样用GitHub actions编译得了😂

**Comment by jadqin** [comment]
> python3.6的话有点老，要不你也跟我一样用GitHub actions编译得了😂

我还是个小白，主要想搞明白系统的构建，我先研究T113这个资料多一点。要是大佬能发下这个的资料给我也是非常感谢。

**Comment by Izumiko** [comment]
你可以参考一下这个repo，他整理的挺全的
https://github.com/yjun123/e-waste

**Comment by houandy** [comment]
这个uboot怎么刷

**Comment by Izumiko** [comment]
> 这个uboot怎么刷

我之前是用dd命令写到镜像开头附近，然后烧录到tf卡再启动，没有写到内置的emmc里面。后来不搞这个了，这个项目就搁置了
